### ISSUE TITLE
7.6 Data Rights - Example 2

### ISSUE THREAD

**Issue by riannella** [EKGF/dprod#83]
The constraint says "Permission to read all the datasets of the product if user is working inside EMEA or APAC"

These implies there needs to a constraint added on the assignee party.

**Comment by joshcornejo** [comment]
fixed policy mistakes:
- to have assignee, converted it to :Agreement
- assignee at this stage must be PartyCollection to have refinement
- changed constraint to refinement as per comment
- changed leftOperand to :spatial
- changed action to :use (there is no "read" defined by default).

@jgeluk

**Comment by rivettp** [comment]
I cannot track down these changes @joshcornejo

**Comment by joshcornejo** [comment]
The changes are https://github.com/EKGF/dprod/blob/develop/examples/data-rights/example.jsonld

I thought they populated the README.md when generated?

**Comment by jgeluk** [comment]
## Analysis

@joshcornejo described the correct ODRL fixes in [this comment](https://github.com/EKGF/dprod/issues/83#issuecomment-2459143693), but these were never applied to the source files. The last commit (3d2b053) only fixed JSON-LD syntax issues — the ODRL modeling problems remained:

1. **`@type: "Offer"`** — An Offer cannot have an assignee. Since the policy description says "if **user** is working inside EMEA or APAC", we need an assignee party, which requires an `Agreement`.
2. **`action: "odrl:read"`** — `read` is not a defined ODRL action. Changed to `odrl:use`.
3. **Spatial constraint on the wrong entity** — The constraint "user is working inside EMEA or APAC" is about *who* can use the data, not *where* the action happens. In ODRL terms, this is a `refinement` on the `assignee` (a `PartyCollection`), not a `constraint` on the permission.

## Changes (branch `DPROD-20`, commit a51d9d3)

**`examples/data-rights/example.jsonld`:**
- Changed `@type` from `"Offer"` to `"Agreement"`
- Changed `action` from `"odrl:read"` to `"odrl:use"`
- Replaced permission-level `constraint` with an `assignee` of type `odrl:PartyCollection` with a spatial `refinement`

**`examples/data-rights/README.md`:**
- Updated inline example to match the corrected ODRL structure

**Comment by riannella** [comment]
ODRL does define "read"  https://www.w3.org/TR/odrl-vocab/#term-read

The spatial constraint should be on the Action not the Parties.

If you want to use an Agreement, then you also need some ID for the assignee.
